apiVersion: apps/v1
kind: Deployment
metadata:
  name: confidential-app-deployment
  labels:
    app: confidential-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: confidential-app
  template:
    metadata:
      labels:
        app: confidential-app
    spec:
      # Use custom service account for Artifact Registry access
      serviceAccountName: confidential-app-sa
      containers:
      - name: confidential-app-container
        # Project ID will be dynamically replaced during deployment
        image: us-central1-docker.pkg.dev/PROJECT_ID_PLACEHOLDER/confidential-repo/confidential-app:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        # Add health checks for better reliability
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5